add beancount.io iOS and Android Apps
siddhantgoel/awesome-beancount pull request #11
Opened 2020-08-30 20:43 UTC by puncsky

2020-09-02 17:39 UTC, siddhantgoel commented
Since these are commercial apps, could you please create a section called "Commercial Apps" and move these two entries there?

2020-09-02 19:04 UTC, puncsky commented
> Since these are commercial apps, could you please create a section called "Commercial Apps" and move these two entries there?

sure, thanks for reviewing!

2020-09-02 19:12 UTC, siddhantgoel requested changes

2020-09-02 19:12 UTC, siddhantgoel commented on README.md
> +- [Beancount.io Android App](https://play.google.com/store/apps/details?id=io.beancount.android) - Add a transaction to your Beancount ledger quickly
Is it possible to reframe the descriptions here to something neutral?

"First-ever App on iOS that visualizes and connects to your Beancount ledger elegantly" sounds a bit advertise-y and ideally I'd like to keep everything on awesome-beancount.com neutral.

One suggestion would be "iOS app for Beancount.io", and the same for the Android app. What do you think?

2020-09-04 15:43 UTC, siddhantgoel requested changes

2020-09-04 15:43 UTC, siddhantgoel commented on README.md
> +- [Beancount.io iOS App](https://apps.apple.com/us/app/id1527950512) - Visualizes and connects to your Beancount ledger on iOS
```suggestion
- [Beancount.io iOS App](https://apps.apple.com/us/app/id1527950512) - Visualizes and connects to your Beancount.io ledger on iOS
```

2020-09-04 15:43 UTC, siddhantgoel commented on README.md
> +- [Beancount.io Android App](https://play.google.com/store/apps/details?id=io.beancount.android) - Visualizes and connects to your Beancount ledger on Android
```suggestion
- [Beancount.io Android App](https://play.google.com/store/apps/details?id=io.beancount.android) - Visualizes and connects to your Beancount.io ledger on Android
```

2020-09-04 20:40 UTC, merged