Update README.md to add StdioA/beancount-bot
siddhantgoel/awesome-beancount pull request #54
Opened 2024-08-22 12:12 UTC by StdioA

2024-08-25 18:42 UTC, siddhantgoel requested changes

2024-08-25 18:42 UTC, siddhantgoel commented on README.md
> +- [Beancount Bot](https://github.com/StdioA/) - Telegram / Mattermost bot to generate new transactions with few words
```suggestion
- [Beancount Bot](https://github.com/StdioA/beancount-bot) - Telegram / Mattermost bot to generate new transactions with few words
```

2024-08-26 00:36 UTC, StdioA commented on README.md
> +- [Beancount Bot](https://github.com/StdioA/) - Telegram / Mattermost bot to generate new transactions with few words
Apologies for my negligence.

2024-08-28 16:30 UTC, siddhantgoel commented on README.md
> +- [Beancount Bot](https://github.com/StdioA/) - Telegram / Mattermost bot to generate new transactions with few words
No worries.

2024-08-28 16:30 UTC, merged